{
 "title": "T-Pot",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Attack Capture by Honeypot",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "Attack Capture By Honeypot",
     "query": "SELECT COUNT(*) FROM honeypot_events\nWHERE $timeFilter\nGROUP BY time($__interval) fill(null)\n"
    }
   ]
  },
  {
   "title": "Honeypot Logs",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "SELECT \"attack_type\", \"src_ip\", \"dest_port\", \"honeypot\", \"protocol\"\nFROM honeypot_events\nORDER BY time DESC\n"
    }
   ]
  },
  {
   "title": "Attacker IP Address",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT COUNT(\"dest_port\") FROM honeypot_events GROUP BY \"src_ip\"\n"
    }
   ]
  },
  {
   "title": "Total Attack ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(*) from honeypot_events\n\n"
    }
   ]
  },
  {
   "title": "Attack Types",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT COUNT(\"dest_port\") FROM honeypot_events GROUP BY \"attack_type\"\n"
    }
   ]
  },
  {
   "title": "Protocol",
   "type": "piechart",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT COUNT(\"dest_port\") FROM honeypot_events GROUP BY \"protocol\"\n\n\n"
    }
   ]
  },
  {
   "title": "Honeypot Attack Count",
   "type": "barchart",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "query": "SELECT COUNT(*) FROM honeypot_events GROUP BY honeypot\n\n"
    }
   ]
  }
 ]
}